#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = awww-daemon
exec-once = awww img /home/syntricy/Pictures/Wallpapers/wallpaper.png

exec = gsettings set org.gnome.desktop.interface gtk-theme "YOUR_DARK_GTK3_THEME"
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"